import json
import sys
import os

# Add backend to path so we can import superchecker
sys.path.insert(0, os.path.abspath(os.path.join(os.path.dirname(__file__), "backend")))
from backend.superchecker import _CheckerState

def main():
    op_path = "/Users/shahidmoosa/Desktop/op.txt"
    if not os.path.exists(op_path):
        print(f"Error: File not found at {op_path}")
        return

    try:
        with open(op_path, "r", encoding="utf-8") as f:
            lines = f.readlines()
    except Exception as e:
        print(f"Error reading op.txt: {e}")
        return

    # Map lines into the format expected by the checker
    logs = [{"message": line.strip()} for line in lines if line.strip()]

    mock_report = {
        "logs": logs,
        "cluster_overview": {
            "rebalance_status": [],
            "cluster_status": []
        },
        "detected_log_patterns": []
    }

    print(f"Loaded {len(logs)} log lines from {op_path}")
    print("Running _CheckerState logic...")
    
    checker = _CheckerState(mock_report)
    checker.run()
    
    print("\n--- Checker Findings ---")
    if not checker.findings:
        print("No findings generated by the checker.")
    else:
        print(json.dumps(checker.findings, indent=2))

if __name__ == "__main__":
    main()